version: "3.8"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
      NEO4J_URI: bolt://neo4j:7687
    depends_on:
      - mongo
      - neo4j

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:5.1
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
